version: '3.8'

services:
  db:
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todo # DB name will have the same value
      POSTGRES_PASSWORD: todo
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "reach", "-U", "reach"]
      interval: 5s
      timeout: 45s
      retries: 10
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
